### ISSUE TITLE
About your message regarding the DeepFaceLive project

### ISSUE THREAD

**Issue by ottocsb** [devjev/human-delay#1]
After reading all of your comments, I believe that you are the most suitable candidate to play the role of Saint Mary. You seem to be asking why an axe killed someone and why face-changing technology scammed your grandmother. Oh my god, whether it is open source or not, there will still be people scamming your grandmother and using axes to kill people. There will also be people using technology to generate videos they need, such as remembering their deceased grandmothers or chopping down trees with an axe. Really, you should go and restrict the use of electricity because without electricity, none of this would happen.

**Comment by ottocsb** [comment]
Someone is using GPT to generate child pornography texts. Why don't you suppress the development of OpenAI? You should just make them bankrupt. The important thing about publishing a mature technology is its users. I seriously suspect that you are part of a team involved in facial recognition AI fraud because your technology has been open-sourced, and ransomware teams can simply hire developers to use it without paying expensive fees to rent your technology, which affects your interests. Oh my goodness!

**Comment by devjev** [comment]
You are not entitled to pollute completely unrelated projects with your pedestrian opinions.
